CREATE USER secure_code IDENTIFIED BY 12345678
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, CREATE VIEW TO secure_code;

GRANT CREATE TABLE TO secure_code;

ALTER USER secure_code QUOTA 100M ON users;
